MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/data/sunyongqi/model/jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'yes'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]
  SHIFT_NUM: 8
  RE_ARRANGE: True
  MCLOSS: True
  FCE: True
  DIST_TRAIN: False
  MFMP: True
INPUT:
  SIZE_TRAIN: [128, 256]
  SIZE_TEST: [128, 256]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('RGBNT100')
 
  ROOT_DIR: ('/data/datasets')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  BASE_LR: 0.001
  MAX_EPOCHS: 120
  IMS_PER_BATCH: 32
  WARMUP_METHOD: 'linear'
  WARMUP_EPOCHS: 10
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 40
  LOG_PERIOD: 20
  EVAL_PERIOD: 1
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2


TEST:
  EVAL: True

  #256
  IMS_PER_BATCH: 64
  RE_RANKING: True
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  
OUTPUT_DIR: './logs/100_mfmp_fce_ic'